/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'category',
      label: '📥 Ingestion Domain',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'domain-ingestion',
        },
      ],
    },
    {
      type: 'category',
      label: '🔍 Retrieval Domain',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'domain-retrieval',
        },
      ],
    },
    {
      type: 'category',
      label: '🧠 Orchestration Domain',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'domain-orchestration',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Operations Domain',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'domain-operations',
        },
      ],
    },
    {
      type: 'category',
      label: '🚀 Applications Domain',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'domain-applications',
        },
      ],
    },
  ],
};

module.exports = sidebars;
